config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
    resources :reviews
  end
  root 'books#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews
  default_scope -> { order('title ASC') }
  validates :user_id, presence: true
  has_one_attached :image
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def home
  end
  
  def index
    if params[:category].blank?
    @book = current_user.books
    else
      @category_id = Category.find_by(name: params[:category]).id
      @book = current_user.books.where(:category_id => @category_id)
    end
  end

  def show
    if @book.reviews.blank?
      @average_review = 0
    else
      @average_review = @book.reviews.average(:rating).round(2)
    end
  end

  def new
    @book = current_user.books.build
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def create
    @book = current_user.books.build(book_params)
    @book.image.attach(params[:book][:image])
    if @book.save
      redirect_to books_path
    else 
      render 'new'
    end
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

    def book_params
      params.require(:book).permit(:title, :description, :author, :language, :user_id, :category_id, :image)
    end

    def find_book
      @book = Book.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_book
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.book_id = @book.id
    @review.user_id = current_user.id
    if @review.save
      redirect_to book_path(@book)
    else
      render 'new'
    end
  end

  def edit
  end

  def update 
    if @review.update(review_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to book_path(@book)
  end

  private

    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def find_book
      @book = Book.find(params[:book_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
  
  
  <%= form_for (@book), :html => { :multipart => true } do |f| %>
      <%= f.label :category_id, "Book Category" %>
      <%= f.select :category_id, @categories, :prompt => "Select a Category" %><br>
      
      <%= f.label :image, "Upload Image" %>
      <%= f.file_field :image %><br>

      <%= f.label :title, "Book Title" %>
      <%= f.text_field :title %><br>

      <%= f.label :description %>
      <%= f.text_field  :description %><br>

      <%= f.label :author %>
      <%= f.text_field :author %><br>

      <%= f.label :language, "Sprache" %>
      <%= f.select :language, [['DE'], ['EN']] %><br>



      <%= f.submit :submit, class: "btn btn-primary" %>
    <% end %>

    

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-book-form">

<h1>Edit Book</h1>
<%= render 'form'%>


	</div>

</div>

app/views/books/home.html.erb
  <div class="center jumbotron">
    <h1>Verwalten Sie ihre Büchersammlung</h1>

   
<% if user_signed_in? == false %>
    <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>

app/views/books/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @book.count == 0 %>

  <h1>There are no books currently in this category</h1>

<% else%>
  
  <div class="row">

  <% @book.each do |book| %>
    <div class="col-xs-6 col-md-4 col-lg-3">
      <%= link_to image_tag(book.image, class: "book"), book_path(book) if book.image.attached?%>
    </div>

  <% end %>

  </div>

<% end %>

app/views/books/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-book-form">

		<h1>New Book</h1>

		<%= render 'form' %>

	</div>

</div>

app/views/books/show.html.erb
  <div class="row">
  
    <div class="col-md-4">

       <%= image_tag(@book.image, class: "book-show") %>
    
    </div>
    
    <div class="col-md-8">
      <div class ="book-info">
        <h2 class="book-title"><%= @book.title %></h2>
        <h3 class="book-author"><span>From </span><%= @book.author %></h3>
        <h2>Average Rating</h2>
        <div class="average-review-rating" data-score=<%= @average_review %>></div>
        <span>Based on <%= @book.reviews.count%> reviews</span>
        <p class="book-desc"><%= @book.description%></p>
        <p><%= @book.language %></p>
      </div>
    </div>
  </div>

  <div class="row">

    <div class="col-md-4">

      <div class="reviews">
       
        <h1>Reviews</h1>
        <%= render @book.reviews %>

        <div>
          <%= link_to "Add Review", new_book_review_path(@book), class: "btn-custom" %>
        </div>
      </div>
    </div>

  </div>

    <div class="links btn-group">

      <%= link_to "Back", books_path, class: "btn btn-custom" %>
      <% if @book.user_id == current_user.id %>
        <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-custom"  %>
        <%= link_to "Delete", book_path(@book), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-custom"  %>

      <% end %>
    </div>

  




<script>
	$('.average-review-rating').raty({
		readOnly: true,
		starHalf:     '<%= image_path 'star-half.png' %>',
            starOff:      '<%= image_path 'star-off.png' %>',
            starOn:       '<%= image_path 'star-on.png' %>',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCatalog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
  
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  

  </head>

  <body>

  <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
    <%= link_to "Home", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav nav mr-auto">
      
        <% if user_signed_in? %>
        <li>
          <%= link_to "Books", books_path, class: "nav-link" %>
        </li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
        <% else %>
          <li>
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
          <li><%= link_to "Log In", new_user_session_path, class: "nav-link" %></li>  
        <% end %>
      </ul>

      <ul class="navbar-nav nav navbar-right">
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
            Filter nach Genre <span class="caret"></span>
          </a>


          <ul class="dropdown-menu" role="menu">
            <%= link_to "All", books_path, class: "nav-link" %>
            <div class="dropdown-divider"></div>
            <% Category.all.each do |category| %>
              <li class=" <%= 'active' if params[:category] == category.name %>">
                <%= link_to category.name, books_path(category: category.name), class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
         
        <% if user_signed_in? %>
          <%= link_to "Add Book", new_book_path, class: "nav-link" %></li>
        <% end %>

        
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
</nav>



 
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="container">
      
      <%= yield %>
      </div>
      
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for([@book, @book.reviews.build]) do |f| %>

  <div id="rating-form">
    <label>Rating </label>
  </div>

  <%= f.label :comment, "Comment" %>
  <%= f.text_field :comment %>
  <%= f.button :submit %>

<% end %>

<script>
  $('#rating-form').raty({
    starHalf:     '<%= image_path 'star-half.png' %>',
            starOff:      '<%= image_path 'star-off.png' %>',
            starOn:       '<%= image_path 'star-on.png' %>',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<div class="review">

  <div class="review-rating" data-score="<%= review.rating %>">
  </div>
  <p class="review-comment"><%= review.comment %></p>

  <div class="links btn-group">

    <%= link_to "Edit", edit_book_review_path(review.book, review), class: "btn btn-custom"  %>
    <%= link_to "Delete", book_review_path(review.book, review), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-custom"  %>
  </div>
</div>

<script>

	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		starHalf:     '<%= image_path 'star-half.png' %>',
            starOff:      '<%= image_path 'star-off.png' %>',
            starOn:       '<%= image_path 'star-on.png' %>'
	});
</script>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= form_for([@book, @review]) do |f| %>
 <div id="rating-form">
    <label>Rating </label>
  </div>
  <%= f.label :comment, "Comment" %>
  <%= f.text_field :comment %>
  <%= f.button :submit %>

<% end %>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>